// Mock data for ENGER v2 matching platform (phase 1 — design first)
// 後で中央 Supabase (enger スキーマ) のデータに差し替える。

export const MOCK = {
  user: { name: "佐々木 拓真", role: "営業 / マッチング担当", initials: "SA", company: "株式会社エイト" },
  kpis: [
    { label: "有効リード", val: 337, unit: "件", chipText: "−75 / 412", chipTone: "flat", tone: "brand", note: "接触前失注 75 件を除く" },
    { label: "接触後失注率", val: "4.5", unit: "%", chipText: "−1.2pt", chipTone: "good", tone: "", note: "15 / 337 件 · 前月比" },
    { label: "ステージ推移率", val: "32", unit: "%", chipText: "+3pt", chipTone: "good", tone: "accent", note: "提案 → 面談 · 前月比" },
    { label: "成約見込み", val: "¥18.4", unit: "M", chipText: "+¥2.1M", chipTone: "good", tone: "warn", note: "3 件成約見込 · 今月" },
  ],
  matchingFeed: [
    { id: "M-2841", job: "決済基盤 / バックエンドリード", company: "三菱UFJ系SIer", skills: ["Java 17", "Spring", "AWS"], score: 94, candidates: 6, status: "open", deadline: "5/28", rate: "¥85万", location: "東京・大手町" },
    { id: "M-2840", job: "EC基盤 React 移行 PM", company: "アパレル大手", skills: ["React", "TypeScript", "PM"], score: 88, candidates: 4, status: "review", deadline: "5/24", rate: "¥95万", location: "リモート可" },
    { id: "M-2839", job: "データ基盤 / Snowflake", company: "通信キャリア子会社", skills: ["Snowflake", "dbt", "Python"], score: 86, candidates: 9, status: "open", deadline: "6/03", rate: "¥80万", location: "リモート" },
    { id: "M-2838", job: "iOS アプリ Swift 刷新", company: "メディアスタートアップ", skills: ["Swift", "SwiftUI"], score: 81, candidates: 3, status: "open", deadline: "5/30", rate: "¥75万", location: "渋谷" },
    { id: "M-2837", job: "業務系 .NET 保守", company: "大手物流", skills: [".NET", "Azure"], score: 72, candidates: 5, status: "draft", deadline: "—", rate: "¥70万", location: "品川" },
  ],
  tasks: [
    { id: 1, kind: "提案", txt: "山田 健介 さんへ「決済基盤PM」提案メール", due: "今日 17:00", lvl: "warn" },
    { id: 2, kind: "面談", txt: "三菱UFJ系SIer 一次面談 候補日調整", due: "明日 10:00", lvl: "" },
    { id: 3, kind: "返信", txt: "アパレル大手 PM 案件 質問への回答", due: "今日 18:30", lvl: "danger" },
    { id: 4, kind: "確認", txt: "通信キャリア子会社 単価交渉ステータス確認", due: "5/24", lvl: "" },
    { id: 5, kind: "登録", txt: "新規パートナー 5名 のスキルシート反映", due: "5/26", lvl: "" },
  ],
  pipeline: [
    { name: "全リード", n: 412, yield: null as number | null },
    { name: "有効リード", n: 337, yield: 82 },
    { name: "接触成功", n: 280, yield: 83 },
    { name: "提案送付", n: 142, yield: 51 },
    { name: "面談設定", n: 45, yield: 32 },
    { name: "成約", n: 12, yield: 27 },
  ],
  lossReasons: [
    { id: "contact", label: "連絡がつかない", n: 60, color: "#c9504a", group: "A", note: "取り込み時点で実質リードとして成立していない" },
    { id: "unmatch", label: "アンマッチ", n: 11, color: "#d97a3a", group: "A", note: "スキル・単価・地域が案件要件と不一致" },
    { id: "dup", label: "重複", n: 4, color: "#c9a73a", group: "A", note: "同一人材・同一案件の重複取り込み" },
    { id: "other", label: "他社決定済み", n: 8, color: "#5a9b6a", group: "B", note: "返信が埋もれて追客遅れ、検討順送り" },
    { id: "decline", label: "人材辞退", n: 7, color: "#3d7fa8", group: "B", note: "ステータス不明・提案タイミングで手遅れ" },
  ],
  initiatives: [
    {
      no: "01", tag: "データ品質ゲート", tone: "warm", target: "原因 A · 75 件", pct: 83,
      title: "取り込み段階で NG を規則化する",
      lede: "「連絡不能・仕様不適合・重複」は以降の提案フローに乗せない。今月の失注 90 件のうち 75 件 （ 83 % ）に効く。",
      rules: [
        { k: "初回返信なし + 7 日経過", v: "自動で NG 候補に変更" },
        { k: "見込み薄 フラグ", v: "毎週 一括レビュー → NG 確定" },
        { k: "取り込み時 重複チェック", v: "メール / 電話番号 / 氏名 の三点一致でアラート" },
        { k: "NG リストの難易度 タグ", v: "「再検対象」「完全 NG」の 2 区分" },
      ],
      progress: { pct: 15, label: "規則ドラフト" }, action: "ルールを設定する", impact: "提案数は減る — 「質指標に表れる」",
    },
    {
      no: "02", tag: "対応プロセスの仕組み化", tone: "cool", target: "原因 B · 15 件", pct: 17,
      title: "採用フローを ENGER に横展開する",
      lede: "受信 → 自動振り分け → 通知 → ステータス管理。採用ですでに回している仕組みを、案件・人材対応にそのまま移す。",
      rules: [
        { k: "返信 自動通知", v: "担当に 5 分以内 プッシュ · 受信箱に埋もれない" },
        { k: "トリアージ振り分け", v: "返信内容 → 「見込み / 保留 / NG」 に自動タグ" },
        { k: "ステータス 表示ルール", v: "ステージ毎 最長滞留日数 を定め、超えたら表示" },
        { k: "トークスクリプト · チェックリスト", v: "シーン別テンプレートで 質を個人依存にしない" },
      ],
      progress: { pct: 8, label: "採用実績あり" }, action: "テンプレートを仕掛ける", impact: "質を個人の熟練度に依存させない",
    },
  ],
  activities: [
    { who: "AI", what: "新着9件のマッチを検出（>85%スコア）", when: "3分前", kind: "ai" },
    { who: "高橋 美保", what: "EC基盤PMに 平野 翔 を提案", when: "12分前", kind: "act" },
    { who: "三菱UFJ系SIer", what: "決済基盤の単価レンジを更新", when: "32分前", kind: "co" },
    { who: "AI", what: "鈴木 一樹 のスキル更新を反映", when: "1時間前", kind: "ai" },
    { who: "渡辺 翔太", what: "成約: メディアSTU iOS刷新", when: "2時間前", kind: "won" },
    { who: "山田 健介", what: "ご返信ありがとうございます…", when: "今朝", kind: "msg" },
  ],
  aiSuggestions: [
    { title: "決済基盤PM × 中村 拓海", reason: "Java 17 + 金融基盤経験 8年, 単価レンジ一致", score: 96, action: "提案を作成" },
    { title: "EC React × 平野 翔", reason: "前回の類似案件で実績, 即日稼働可能", score: 93, action: "提案を作成" },
    { title: "Snowflake × 佐藤 千夏", reason: "dbt 認定保持, 通信業界経験", score: 91, action: "提案を作成" },
  ],
  job: {
    id: "M-2841", title: "決済基盤 / バックエンドリード", company: "三菱UFJ系SIer (匿名)",
    location: "東京・大手町（週2リモート）", rate: "¥80–95万 / 月", period: "2026/06 開始 〜 1年（延長可）",
    seats: 2, posted: "5/19", deadline: "5/28",
    skills: ["Java 17", "Spring Boot", "Kafka", "AWS", "金融基盤", "英語: 読み書き"],
    nice: ["決済領域経験", "リードPjM", "ISO 8583"],
    description: "リアルタイム決済基盤の刷新フェーズ2。レガシーCOBOL層からの段階移行を担当するバックエンドリード。SRE志向のあるエンジニアを歓迎します。",
    contact: "原 由紀子（顧客窓口）",
  },
  companies: [
    { id: "C-001", name: "三菱UFJ系SIer", initials: "MU", tier: "A", industry: "金融システム", activeJobs: 6, lastDeals: 4, totalRevenue: "¥142M", owner: "佐々木", ownerInit: "SA", status: "主要", lastActivity: "3時間前", relation: 92, color: "#0095D9", note: "決済基盤 / 勘定系 を中心に長期で依頼" },
    { id: "C-002", name: "アパレル大手 A", initials: "AP", tier: "A", industry: "小売 / EC", activeJobs: 4, lastDeals: 9, totalRevenue: "¥98M", owner: "高橋", ownerInit: "TM", status: "主要", lastActivity: "昨日", relation: 88, color: "#3f634d", note: "EC リシステム React 移行を中心に" },
    { id: "C-003", name: "通信キャリア子会社", initials: "TC", tier: "A", industry: "通信 / IT", activeJobs: 5, lastDeals: 7, totalRevenue: "¥86M", owner: "渡辺", ownerInit: "WS", status: "拡大中", lastActivity: "5/19", relation: 85, color: "#7a5cc4", note: "データ基盤 Snowflake / dbt 案件が広がる" },
    { id: "C-004", name: "メディアSTU", initials: "MS", tier: "B", industry: "メディア", activeJobs: 2, lastDeals: 3, totalRevenue: "¥32M", owner: "佐々木", ownerInit: "SA", status: "主要", lastActivity: "昨日", relation: 78, color: "#d97a3a", note: "スタートアップ / iOS · React Native 案件中心" },
    { id: "C-005", name: "大手物流", initials: "LG", tier: "B", industry: "物流", activeJobs: 3, lastDeals: 6, totalRevenue: "¥54M", owner: "高橋", ownerInit: "TM", status: "主要", lastActivity: "5/18", relation: 72, color: "#5a9b6a", note: ".NET / 業務系 中心、改修多め" },
    { id: "C-006", name: "SaaS BtoB スタッフ", initials: "SB", tier: "B", industry: "SaaS", activeJobs: 2, lastDeals: 1, totalRevenue: "¥18M", owner: "渡辺", ownerInit: "WS", status: "新規", lastActivity: "5/14", relation: 65, color: "#0095D9", note: "SRE / K8s 移行、長期見込み" },
    { id: "C-007", name: "FinTechスタートアップ", initials: "FT", tier: "B", industry: "FinTech", activeJobs: 1, lastDeals: 2, totalRevenue: "¥28M", owner: "高橋", ownerInit: "TM", status: "主要", lastActivity: "5/16", relation: 70, color: "#3d7fa8", note: "進行中 1 件 / 継続検討" },
    { id: "C-008", name: "電力業界子会社", initials: "EP", tier: "C", industry: "インフラ", activeJobs: 1, lastDeals: 3, totalRevenue: "¥21M", owner: "佐々木", ownerInit: "SA", status: "主要", lastActivity: "5/13", relation: 60, color: "#c9a73a", note: "長い付き合い / 規模小さめだが安定" },
    { id: "C-009", name: "コンサル大手", initials: "CN", tier: "C", industry: "コンサル", activeJobs: 0, lastDeals: 2, totalRevenue: "¥14M", owner: "高橋", ownerInit: "TM", status: "休眠", lastActivity: "4/22", relation: 42, color: "#94a3b8", note: "3 ヶ月間連絡なし / 要フォロー" },
    { id: "C-010", name: "ゲーム業界 B", initials: "GB", tier: "C", industry: "ゲーム", activeJobs: 0, lastDeals: 1, totalRevenue: "¥8M", owner: "渡辺", ownerInit: "WS", status: "休眠", lastActivity: "3/14", relation: 35, color: "#94a3b8", note: "一回提案 / 不採用、要件不一致" },
    { id: "C-011", name: "医療系 SaaS", initials: "MH", tier: "B", industry: "ヘルスケア", activeJobs: 2, lastDeals: 0, totalRevenue: "¥12M", owner: "佐々木", ownerInit: "SA", status: "新規", lastActivity: "5/20", relation: 68, color: "#5a9b6a", note: "初取引 / 2 案件進行中" },
    { id: "C-012", name: "教育業界 PF", initials: "EP", tier: "C", industry: "教育", activeJobs: 1, lastDeals: 1, totalRevenue: "¥9M", owner: "高橋", ownerInit: "TM", status: "新規", lastActivity: "5/15", relation: 55, color: "#d97a3a", note: "LMS 評価 進行中" },
  ],
  progressItems: [
    { id: "PR-411", stage: "新規提案", job: "決済基盤 / BE リード", company: "三菱UFJ系SIer", candidate: "中村 拓海", cInit: "NT", rate: "¥90万", score: 96, owner: "佐々木", oInit: "SA", due: "今日 17:00", dueT: "danger", daysIn: 1, next: "提案メール送信", ai: true },
    { id: "PR-410", stage: "新規提案", job: "EC React 移行 PM", company: "アパレル大手 A", candidate: "平野 翔", cInit: "HS", rate: "¥82万", score: 93, owner: "高橋", oInit: "TM", due: "5/22 12:00", dueT: "warn", daysIn: 1, next: "提案資料作成", ai: true },
    { id: "PR-409", stage: "新規提案", job: "Snowflake データ基盤", company: "通信キャリア子会社", candidate: "佐藤 千夏", cInit: "ST", rate: "¥78万", score: 91, owner: "渡辺", oInit: "WS", due: "5/23", dueT: "", daysIn: 1, next: "初回説明", ai: true },
    { id: "PR-405", stage: "提案中", job: "FinTech BE 開発", company: "三菱UFJ系SIer", candidate: "高橋 翔", cInit: "TS", rate: "¥82万", score: 88, owner: "佐々木", oInit: "SA", due: "5/24", dueT: "warn", daysIn: 4, next: "先方担当の返信待ち", ai: false },
    { id: "PR-404", stage: "提案中", job: "iOS Swift 刷新", company: "メディアSTU", candidate: "鈴木 一樹", cInit: "SK", rate: "¥75万", score: 84, owner: "佐々木", oInit: "SA", due: "5/26", dueT: "", daysIn: 5, next: "質問への回答", ai: false },
    { id: "PR-403", stage: "提案中", job: ".NET 業務系 保守", company: "大手物流", candidate: "原田 真希", cInit: "HM", rate: "¥70万", score: 78, owner: "高橋", oInit: "TM", due: "5/24", dueT: "warn", daysIn: 3, next: "担当者調整", ai: false },
    { id: "PR-402", stage: "提案中", job: "SRE / K8s 移行", company: "SaaS BtoB スタッフ", candidate: "井上 さくら", cInit: "IS", rate: "¥88万", score: 79, owner: "渡辺", oInit: "WS", due: "5/28", dueT: "", daysIn: 6, next: "社内評議待ち", ai: false },
    { id: "PR-391", stage: "面談調整", job: "決済基盤 / BE リード", company: "三菱UFJ系SIer", candidate: "中村 拓海", cInit: "NT", rate: "¥90万", score: 96, owner: "佐々木", oInit: "SA", due: "明日 10:00", dueT: "warn", daysIn: 2, next: "一次面談 セットアップ", ai: false },
    { id: "PR-390", stage: "面談調整", job: "EC React 移行", company: "アパレル大手 A", candidate: "平野 翔", cInit: "HS", rate: "¥82万", score: 93, owner: "高橋", oInit: "TM", due: "5/24", dueT: "warn", daysIn: 3, next: "二次面談 社内調整", ai: false },
    { id: "PR-381", stage: "条件交渉", job: "決済基盤 / BE", company: "三菱UFJ系SIer", candidate: "鈴木 一樹", cInit: "SK", rate: "¥85万", score: 91, owner: "佐々木", oInit: "SA", due: "5/24", dueT: "warn", daysIn: 8, next: "単価調整 ±¥5万", ai: false },
    { id: "PR-380", stage: "条件交渉", job: "PM / Fintech", company: "FinTechスタートアップ", candidate: "森 健介", cInit: "MK", rate: "¥100万", score: 88, owner: "高橋", oInit: "TM", due: "5/27", dueT: "", daysIn: 6, next: "契約期間 調整", ai: false },
    { id: "PR-371", stage: "成約間近", job: "決済基盤 / BE", company: "三菱UFJ系SIer", candidate: "中村 拓海", cInit: "NT", rate: "¥90万", score: 96, owner: "佐々木", oInit: "SA", due: "今週中", dueT: "", daysIn: 12, next: "最終オファー 提示", ai: false },
    { id: "PR-370", stage: "成約間近", job: "EC React 移行", company: "アパレル大手 A", candidate: "平野 翔", cInit: "HS", rate: "¥82万", score: 93, owner: "高橋", oInit: "TM", due: "5/26", dueT: "warn", daysIn: 10, next: "契約書 送付", ai: false },
  ],
  candidates: [
    { id: "P-04127", name: "中村 拓海", initials: "NT", title: "バックエンドリード / 金融基盤", exp: "12y", company: "フリーランス", rate: "¥90万", avail: "6/01〜", location: "東京", skills: ["Java", "Spring", "Kafka", "AWS", "金融"], score: 96, why: ["Java 17 + Spring Boot ✓", "金融基盤 8年 ✓", "希望単価 一致", "読み書き英語 ✓"], status: "提案可", saved: true },
    { id: "P-04138", name: "鈴木 一樹", initials: "SK", title: "シニアエンジニア", exp: "9y", company: "パートナーA", rate: "¥85万", avail: "6/15〜", location: "リモート", skills: ["Java", "AWS", "Kafka", "SRE"], score: 91, why: ["AWS 認定 ✓", "Kafka 運用 5年 ✓", "稼働開始やや遅め △"], status: "提案中", saved: true },
    { id: "P-04201", name: "高橋 翔", initials: "TS", title: "フルスタック / FinTech", exp: "7y", company: "パートナーB", rate: "¥82万", avail: "6/01〜", location: "東京", skills: ["Java", "React", "AWS", "決済"], score: 88, why: ["決済領域 3年 ✓", "Spring 経験あり ✓", "リードPjM 未経験 △"], status: "提案可", saved: false },
    { id: "P-04088", name: "佐藤 千夏", initials: "ST", title: "バックエンド / データ寄り", exp: "8y", company: "パートナーA", rate: "¥78万", avail: "6/01〜", location: "リモート", skills: ["Java", "Snowflake", "dbt"], score: 84, why: ["Java 経験 6年 ✓", "Kafka 未経験 ✗", "希望単価 やや低め ✓"], status: "提案可", saved: false },
    { id: "P-04222", name: "原田 真希", initials: "HM", title: "バックエンド / 業務系", exp: "6y", company: "フリーランス", rate: "¥75万", avail: "7/01〜", location: "東京", skills: ["Java", "Spring", "AWS"], score: 80, why: ["Spring Boot 3年 ✓", "金融未経験 △", "稼働開始遅め △"], status: "提案可", saved: false },
    { id: "P-04305", name: "森 健介", initials: "MK", title: "PjM / 金融基盤", exp: "14y", company: "パートナーC", rate: "¥100万", avail: "6/01〜", location: "東京", skills: ["PjM", "金融", "Java"], score: 78, why: ["金融基盤 10年 ✓", "Java 実装距離あり △", "単価上振れ △"], status: "提案可", saved: false },
    { id: "P-04412", name: "井上 さくら", initials: "IS", title: "Kafka スペシャリスト", exp: "7y", company: "フリーランス", rate: "¥88万", avail: "6/15〜", location: "リモート", skills: ["Kafka", "Java", "SRE"], score: 76, why: ["Kafka 5年 ✓", "金融未経験 △"], status: "提案可", saved: false },
  ],
};

export type Mock = typeof MOCK;
